# Gems
gems:
  - jekyll-paginate
  - jekyll-gist
  - redcarpet

markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty
# relative_permalinks: true

# Setup
title:            karai
tagline:          'music site'
description:      ''
url:              http://karaimusic.com
baseurl:          ''

author:
  name:           'crabs'
  url:            

paginate:         5

# Custom vars
version:          2.1.0

